package com.codeop.store.config;

import com.codeop.store.model.Product;
import com.codeop.store.repository.CartRepository;
import com.codeop.store.repository.OrderRepository;
import com.codeop.store.repository.ProductRepository;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class DataSeeder implements CommandLineRunner {

    private final ProductRepository productRepository;
    private final CartRepository cartRepository;
    private final OrderRepository orderRepository;

    public DataSeeder(ProductRepository productRepository,
                      CartRepository cartRepository,
                      OrderRepository orderRepository) {
        this.productRepository = productRepository;
        this.cartRepository = cartRepository;
        this.orderRepository = orderRepository;
    }

    @Override
    public void run(String... args) {
        if (productRepository.count() > 0) {
            return;
        }

        cartRepository.deleteAll();
        orderRepository.deleteAll();

        List<Product> products = List.of(
                build("Signal Dentifrice Blancheur 100 ml",
                        "Whitening toothpaste for everyday use.",
                        "MOR-ORAL-001", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("18.00")),
                build("Sensodyne Complete Care 75 ml",
                        "For sensitive teeth and enamel protection.",
                        "MOR-ORAL-002", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("40.00")),
                build("Sanogyl Mouthwash Antibacterial 500 ml",
                        "Antibacterial mouthwash with mint and eucalyptus.",
                        "MOR-ORAL-003", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("99.00")),
                build("Denti Smile Charcoal Mouthwash 300 ml",
                        "Activated charcoal mouthwash for fresh breath.",
                        "MOR-ORAL-004", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("90.00")),
                build("Coslys Charcoal Toothpaste",
                        "Natural toothpaste with vegetal charcoal.",
                        "MOR-ORAL-005", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("75.00")),
                build("Cattier Kids Toothpaste 7+ 50 ml",
                        "Gentle toothpaste for kids.",
                        "MOR-ORAL-006", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("101.00")),
                build("Curasept EcoBio Toothpaste 75 ml",
                        "Bio-friendly dental care.",
                        "MOR-ORAL-007", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("65.00")),
                build("Oral-B Mouthwash Mint 250 ml",
                        "Classic mint mouthwash.",
                        "MOR-ORAL-008", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("36.00")),
                build("Colgate Toothpaste Classic",
                        "Everyday toothpaste option.",
                        "MOR-ORAL-009", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("30.00")),
                build("Carrefour Toothpaste",
                        "Budget supermarket toothpaste.",
                        "MOR-ORAL-010", "Oral Hygiene",
                        "https://via.placeholder.com/600x400?text=Oral+Hygiene",
                        new BigDecimal("20.00")),

                build("Rexona Antiperspirant",
                        "Popular everyday antiperspirant.",
                        "MOR-DEO-001", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("95.00")),
                build("Vichy 48h Antiperspirant",
                        "Strong sweat protection formula.",
                        "MOR-DEO-002", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("110.00")),
                build("SVR Deo-Creme Anti-Transpirant",
                        "Cream deodorant for heavy sweat.",
                        "MOR-DEO-003", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("110.00")),
                build("Camomilla Blu Deodorant Roll 50 ml",
                        "Natural scent roll-on deodorant.",
                        "MOR-DEO-004", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("113.00")),
                build("Secret Invisible Deodorant 73 ml",
                        "Balanced pH with invisible finish.",
                        "MOR-DEO-005", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("66.00")),
                build("Zidaman Solid Deodorant",
                        "Solid deodorant with essential oils.",
                        "MOR-DEO-006", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("65.00")),
                build("So'Bio Etic Deodorant 24h",
                        "Bio-oriented deodorant.",
                        "MOR-DEO-007", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("67.00")),
                build("Axe Body Spray",
                        "Classic men's deodorant.",
                        "MOR-DEO-008", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("70.00")),
                build("Dove Men+Care Deodorant",
                        "Everyday anti-odor protection.",
                        "MOR-DEO-009", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("80.00")),
                build("Carrefour Deodorant",
                        "Budget supermarket deodorant.",
                        "MOR-DEO-010", "Deodorants",
                        "https://via.placeholder.com/600x400?text=Deodorants",
                        new BigDecimal("40.00")),

                build("Natracare Ultra Pads 12 pcs",
                        "Natural cotton pads with wings.",
                        "MOR-PAD-001", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("52.00")),
                build("Nana Maternity Pads 15 pcs",
                        "Maternity and overnight pads.",
                        "MOR-PAD-002", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("32.00")),
                build("Abena Maternity Pads",
                        "High-absorbency maternity pads.",
                        "MOR-PAD-003", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("57.00")),
                build("Tadam' Hygiene Pads",
                        "Local Moroccan brand pads.",
                        "MOR-PAD-004", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("50.00")),
                build("Caroli Hygiene Pads",
                        "Budget supermarket pads.",
                        "MOR-PAD-005", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("27.00")),
                build("Flowflex Tampons",
                        "Tampon option with applicator.",
                        "MOR-PAD-006", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("45.00")),
                build("Always Maxi Pads",
                        "Classic pad line.",
                        "MOR-PAD-007", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("180.00")),
                build("U By Kotex Pads",
                        "Imported pad option.",
                        "MOR-PAD-008", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("160.00")),
                build("Playtex Tampons",
                        "Imported tampon option.",
                        "MOR-PAD-009", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("193.00")),
                build("Pinkie Period Starter Pads",
                        "Organic cotton pads.",
                        "MOR-PAD-010", "Female Hygiene",
                        "https://via.placeholder.com/600x400?text=Female+Hygiene",
                        new BigDecimal("179.00")),

                build("Pampers Baby-Dry",
                        "Up to 12h dryness, strong absorption.",
                        "MOR-DIA-001", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("160.00")),
                build("Pampers Active Baby",
                        "Extra comfort for moving babies.",
                        "MOR-DIA-002", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("175.00")),
                build("Huggies Ultra Comfort",
                        "Soft cotton feel for sensitive skin.",
                        "MOR-DIA-003", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("145.00")),
                build("Dalaa Economy Jumbo Pack",
                        "Affordable with good absorption.",
                        "MOR-DIA-004", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("100.00")),
                build("Fine Baby Classic",
                        "Good quality mid-range diapers.",
                        "MOR-DIA-005", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("120.00")),
                build("TENA Slip Pants",
                        "High absorption adult diapers.",
                        "MOR-DIA-006", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("185.00")),
                build("Abena Pants Slips",
                        "Hospital-grade incontinence diapers.",
                        "MOR-DIA-007", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("165.00")),
                build("MoliCare Adult Diapers",
                        "Very high absorbency.",
                        "MOR-DIA-008", "Diapers",
                        "https://via.placeholder.com/600x400?text=Diapers",
                        new BigDecimal("200.00")),

                build("CLEAN Laundry Detergent 30 Washes",
                        "Laundry detergent for 30 washes.",
                        "MOR-CLN-001", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("99.00")),
                build("CLEAN Dish Soap Almond",
                        "Dishwashing liquid.",
                        "MOR-CLN-002", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("27.00")),
                build("Clorox Bleach",
                        "Standard household disinfectant.",
                        "MOR-CLN-003", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("25.00")),
                build("Carrefour Multi-Use Cleaner",
                        "Budget multi-surface cleaner.",
                        "MOR-CLN-004", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("30.00")),
                build("Mr. Propre Multi-Surface",
                        "Everyday multi-surface cleaner.",
                        "MOR-CLN-005", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("45.00")),
                build("Ariel Laundry Powder",
                        "Popular washing powder.",
                        "MOR-CLN-006", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("120.00")),
                build("Sunlight Dish Soap",
                        "Dish and hand wash.",
                        "MOR-CLN-007", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("30.00")),
                build("Glass and Window Cleaner",
                        "Typical window cleaner.",
                        "MOR-CLN-008", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("30.00")),
                build("Megaplast Sponges and Scrub Pads",
                        "Cleaning tools pack.",
                        "MOR-CLN-009", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("17.00")),
                build("Laundry Softener",
                        "Fabric softener product.",
                        "MOR-CLN-010", "Cleaning & Washing",
                        "https://via.placeholder.com/600x400?text=Cleaning",
                        new BigDecimal("60.00")),

                build("So Bio Shower Gel Peach 450 ml",
                        "Natural shower gel.",
                        "MOR-BODY-001", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("79.90")),
                build("Cattier Orange Blossom Shower Gel 1 L",
                        "Large bottle natural body wash.",
                        "MOR-BODY-002", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("150.00")),
                build("Bio Frequent Use Shampoo",
                        "Eco-friendly shampoo for daily use.",
                        "MOR-BODY-003", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("110.00")),
                build("Kids 2-in-1 Shampoo and Wash",
                        "Child body and hair wash.",
                        "MOR-BODY-004", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("180.00")),
                build("Savon Beldi Black Soap",
                        "Traditional Moroccan hammam soap.",
                        "MOR-BODY-005", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("20.00")),
                build("CeraVe Moisturizing Body Wash",
                        "Dermatologist recommended body wash.",
                        "MOR-BODY-006", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("110.00")),
                build("Nivea Shower Cream",
                        "Common body wash brand.",
                        "MOR-BODY-007", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("75.00")),
                build("Corine de Farme Body Cleanser",
                        "Gentle family soap brand.",
                        "MOR-BODY-008", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("85.00")),
                build("Biolane Gentle Body Wash",
                        "Baby-friendly gentle wash.",
                        "MOR-BODY-009", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("95.00")),
                build("BYPHASSE Body Care",
                        "Budget personal wash brand.",
                        "MOR-BODY-010", "Body & Shower",
                        "https://via.placeholder.com/600x400?text=Body+Care",
                        new BigDecimal("70.00"))
        );

        productRepository.saveAll(products);
    }

    private Product build(String name, String description, String sku, String category, String imageUrl,
                          BigDecimal price) {
        Product product = new Product();
        product.setName(name);
        product.setDescription(description);
        product.setSku(sku);
        product.setCategory(category);
        product.setImageUrl(imageUrl);
        product.setPrice(price);
        product.setCurrency("MAD");
        product.setStockQuantity(100);
        product.setActive(true);
        return product;
    }
}
